# Generated by Django 3.1.5 on 2021-01-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandleSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=120)),
                ('companyLink', models.CharField(max_length=200)),
                ('companyPhone', models.CharField(max_length=20)),
                ('companyAddress', models.CharField(max_length=150)),
            ],
        ),
    ]
