# Generated by Django 3.1.5 on 2021-02-15 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_candlesitecomments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='candlesite',
            name='companyAddress',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='candlesite',
            name='companyLink',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='candlesite',
            name='companyName',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='candlesite',
            name='companyPhone',
            field=models.CharField(max_length=24),
        ),
        migrations.AddField(
            model_name='candlesitecomments',
            name='commentator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sites.commentator'),
            preserve_default=False,
        ),
    ]
