# Generated by Django 3.1.5 on 2021-02-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_auto_20210215_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candlesitecomments',
            name='comment',
            field=models.CharField(max_length=1024),
        ),
    ]
