# Generated by Django 3.1.5 on 2021-02-21 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_auto_20210217_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candlesitecomments',
            name='commentator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sites.commentator'),
        ),
    ]
